### ISSUE TITLE
Copying files when building

### ISSUE THREAD

**Issue by markfinger** [bahmutov/compiled#14]
Hi,

Not sure if this is supported or not, I couldn't find anything in the README.

Babel's CLI has a `--copy-files` param that causes the compiler to also copy over every non-JS file that it finds. I find this particularly useful as I a lot of my projects use JSON and static assets as part of the test suite (which also lives in `/src`).

Is there any support - or intention to support - a similar feature?

**Comment by bahmutov** [comment]
Hmm, no plans for this, this could be another tool to run on `postinstall`, like (assuming the tool is called "recursive-copy")

``` json
{
  "scripts": {
    "postinstall": "compile && recursive-copy"
  }
}
```

**Comment by markfinger** [comment]
Good idea.

I'll just poke around and prototype something when I end up needing it.
