### ISSUE TITLE
Rollup's role in the compile stage

### ISSUE THREAD

**Issue by markfinger** [bahmutov/compiled#15]
I gather from a scan of the codebase that Rollup is used in the compile stage. Is it possible to omit it?

My use-case would be to have a package compiled using the feature-flag detection and the subsequent conditional application of babel transforms, but I'd rather not use rollup (if possible). For context, I'd prefer to maintain some semblance of my codebase's file structure.

**Comment by markfinger** [comment]
Oh, thanks for all the work on this! :smiley:

**Comment by bahmutov** [comment]
The rollup runs as a very first step in the `build` stage, not during client-side `compile` stage. We could make it optional, but I really like the rollup (tree shaking, import / export support is the best). If you want, you can probably implement a config file option to skip Rollup and work off the dirs, I would be open to merging it.

**Comment by markfinger** [comment]
Cool, thanks.

I'll muse over the various parts and touch base if/when I get to a point of needing the functionality.
